CREATE TABLE users (
    handle TEXT PRIMARY KEY,
    email TEXT,
    vk_id TEXT,
    open_id TEXT,
    first_name TEXT,
    last_name TEXT,
    country TEXT,
    city TEXT,
    organization TEXT,
    contribution INTEGER NOT NULL DEFAULT 0,
    rank TEXT,
    rating INTEGER NOT NULL DEFAULT 0,
    max_rank TEXT,
    max_rating INTEGER NOT NULL DEFAULT 0,
    last_online_time_seconds INTEGER NOT NULL DEFAULT 0,
    registration_time_seconds INTEGER NOT NULL DEFAULT 0,
    friend_of_count INTEGER NOT NULL DEFAULT 0,
    avatar_url TEXT,
    title_photo_url TEXT,
    added_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_crawl_at TIMESTAMP
);

CREATE TABLE problems (
    id SERIAL PRIMARY KEY,
    contest_id INTEGER NOT NULL DEFAULT 0,
    problemset_name TEXT,
    index TEXT NOT NULL,
    name TEXT,
    type TEXT,
    points REAL NOT NULL DEFAULT 0,
    rating INTEGER NOT NULL DEFAULT 0,
    tags TEXT[] NOT NULL DEFAULT '{}',
    UNIQUE (contest_id, index)
);

CREATE TABLE submissions (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_handle TEXT NOT NULL,
    language TEXT,
    contest_id INTEGER NOT NULL DEFAULT 0,
    creation_time_seconds INTEGER NOT NULL DEFAULT 0,
    relative_time_seconds INTEGER NOT NULL DEFAULT 0,
    problem_id INTEGER NOT NULL DEFAULT 0,
    programming_language TEXT,
    verdict TEXT,
    test_set TEXT,
    passed_test_count INTEGER NOT NULL DEFAULT 0,
    time_consumed_millis INTEGER NOT NULL DEFAULT 0,
    memory_consumed_bytes INTEGER NOT NULL DEFAULT 0,
    points REAL NOT NULL DEFAULT 0,
    source_code TEXT,
    problem_name TEXT,
    submitted_at TIMESTAMP,
    crawled_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    analyzed BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE analyses (
    id SERIAL PRIMARY KEY,
    submission_id INTEGER NOT NULL,
    ai_confidence DOUBLE PRECISION NOT NULL DEFAULT 0,
    too_clean BOOLEAN NOT NULL DEFAULT FALSE,
    too_clean_evidence TEXT,
    textbook_comments BOOLEAN NOT NULL DEFAULT FALSE,
    textbook_evidence TEXT,
    perfect_naming BOOLEAN NOT NULL DEFAULT FALSE,
    naming_evidence TEXT,
    ai_pattern BOOLEAN NOT NULL DEFAULT FALSE,
    pattern_evidence TEXT,
    too_perfect BOOLEAN NOT NULL DEFAULT FALSE,
    perfect_evidence TEXT,
    wrong_style BOOLEAN NOT NULL DEFAULT FALSE,
    style_evidence TEXT,
    data_structures TEXT,
    algorithms TEXT,
    time_complexity TEXT,
    space_complexity TEXT,
    difficulty_score INTEGER NOT NULL DEFAULT 0,
    explanation TEXT,
    raw_json TEXT,
    analyzed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (submission_id)
);

CREATE TABLE user_scores (
    handle TEXT PRIMARY KEY,
    rating INTEGER NOT NULL DEFAULT 0,
    ds_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    algorithm_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    ai_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    overall_score DOUBLE PRECISION NOT NULL DEFAULT 0,
    total_submissions INTEGER NOT NULL DEFAULT 0,
    analyzed_submissions INTEGER NOT NULL DEFAULT 0,
    ai_detected_count INTEGER NOT NULL DEFAULT 0,
    ai_usage_rate DOUBLE PRECISION NOT NULL DEFAULT 0,
    level TEXT NOT NULL DEFAULT 'BEGINNER',
    top_data_structure TEXT,
    top_algorithm TEXT,
    last_evaluated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS settings (
    key VARCHAR(100) PRIMARY KEY,
    value TEXT NOT NULL DEFAULT ''
);

CREATE INDEX submissions_user_handle_idx ON submissions (user_handle);
CREATE INDEX submissions_problem_id_idx ON submissions (problem_id);
CREATE INDEX analyses_submission_id_idx ON analyses (submission_id);
CREATE INDEX problems_rating_idx ON problems (rating);
CREATE INDEX user_scores_overall_score_idx ON user_scores (overall_score);
